# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HU1Kmo3cLb6ABrXMj_9ZU1LwGDUvlkcm
"""

import pandas as pd

dados = [
    [1, 25, "M", "BH", 3000, 720, 5, 2.5, "Sim", 1],
    [2, 34, "F", "SP", 7000, 800, 10, 1.8, "Sim", 0],
    [3, 29, "M", "RJ", 4500, 650, 3, 3.2, "Não", 1],
    [4, 41, "F", "BH", 9000, 820, 15, 2.0, "Sim", 0],
    [5, 22, "M", "POA", 2000, 600, 1, 4.0, "Não", 1]
]

colunas = [
    "id",
    "idade",
    "genero",
    "cidade",
    "renda",
    "score_credito",
    "tempo_emprego",
    "gasto_mensal",
    "possui_cartao",
    "label"
]

df = pd.DataFrame(dados, columns=colunas)

df.head(1)

"""Identificação de atributos  

Classifique as colunas em:  

identificador direto  
quasi-identificadores  
atributos sensíveis  
atributos não sensíveis  
"""

del df["id"]

df.head(2)

# pii = df['idade']
qi  = df[['idade', 'genero', 'cidade']]
ats = df[['renda', 'gasto_mensal', 'possui_cartao']]
ans = df[['score_credito', 'tempo_emprego']]

"""Com os quasidentificadores escolhidos (idade, genero e cidade) é possível realizar uma combinação para encontrar algum indivíduo

Usando os QIs escolhidos:  

Agrupe os registros  
Conte quantas vezes cada combinação aparece  

Pergunta:  
O dataset é 2-anônimo?
"""

def isKanonymous(qi, k):
  contagem = qi.groupby(['idade', 'genero', 'cidade']).size()
  for i in contagem:
    if i < k:
      return False
    return True

r = isKanonymous(qi, 2)
print(r)

